include ../common.mk

all:
	@echo 'const size_t GFQ_DATA_LEN=$(GFQ_DATA_LEN);' > v1/gfq/GFQConfig.inc
	@echo 'const size_t GFQ_DATA_LEN=$(GFQ_DATA_LEN);' > v2/gfq/GFQConfig.inc

clean:
	@$(RM) v1/gfq/GFQConfig.inc
	@$(RM) v2/gfq/GFQConfig.inc
