#ifndef ANF_BENCODINGMESSAGE_H
#define ANF_BENCODINGMESSAGE_H

#include "anf/Utility.h"

ANF_NAMESPACE_START

enum
{
    // [0x0000 ~ 0x000F] for network protocol
    BENC_TAG_SEQ_NO          = 0x0000,
    BENC_TAG_CMD_ID          = 0x0001,
    BENC_TAG_PROTOCOL_NAME   = 0x0002,
    BENC_TAG_ERROR_TYPE      = 0x0003,
    BENC_TAG_ERROR_CODE      = 0x0004,
    BENC_TAG_ROUTE_INFO1     = 0x0005,
    BENC_TAG_ROUTE_INFO2     = 0x0006,
    BENC_TAG_ROUTE_INFO3     = 0x0007,
    BENC_TAG_USER_BEGIN      = 0x0008,

    // [0x0010 ~ 0x002F] for scp
    SCP_TAG_REQUEST      = 0x0010,
    SCP_TAG_TON          = 0x0011,
    SCP_TAG_NPI          = 0x0012,
    SCP_TAG_VAL          = 0x0013,
    SCP_TAG_MSID         = 0x0014,
    SCP_TAG_RATE         = 0x0015,
    SCP_TAG_TYPE         = 0x0016,
    SCP_TAG_CDRTYPE      = 0x0017,
    SCP_TAG_DISCOUNT     = 0x0018,
    SCP_TAG_COD          = 0x0019,
    SCP_TAG_LEN          = 0x001A,
    SCP_TAG_DATA         = 0x001B,
    SCP_TAG_SPID         = 0x001C,
    SCP_TAG_SERVICEID    = 0x001D,
    SCP_TAG_MSGID        = 0x001E,
    SCP_TAG_SRCGW        = 0x001F,
    SCP_TAG_GWID         = 0x0020,
    SCP_TAG_SMCADDR      = 0x0021,
    SCP_TAG_PRI          = 0x0022,
    SCP_TAG_MSTAT        = 0x0023,
    SCP_TAG_MSGSEQ       = 0x0024,
    SCP_TAG_STAT         = 0x0025,

    // [0x0030 ~ 0x004F] for smmc
    SMMC_TAG_SERVICE_TYPE                = 0x0030,
    SMMC_TAG_SOURCE_ADDR_TON             = 0x0031,
    SMMC_TAG_SOURCE_ADDR_NPI             = 0x0032,
    SMMC_TAG_SOURCE_ADDR                 = 0x0033,
    SMMC_TAG_DEST_ADDR_TON               = 0x0034,
    SMMC_TAG_DEST_ADDR_NPI               = 0x0035,
    SMMC_TAG_DESTINATION_ADDR            = 0x0036,
    SMMC_TAG_ESM_CLASS                   = 0x0037,
    SMMC_TAG_PROTOCOL_ID                 = 0x0038,
    SMMC_TAG_PRIORITY_FLAG               = 0x0039,
    SMMC_TAG_SCHEDULE_DELIVERY_TIME      = 0x003A,
    SMMC_TAG_VALIDITY_PERIOD             = 0x003B,
    SMMC_TAG_REGISTERED_DELIVERY_FLAG    = 0x003C,
    SMMC_TAG_REPLACE_IF_PRESENT_FLAG     = 0x003D,
    SMMC_TAG_DATA_CODING                 = 0x003E,
    SMMC_TAG_SM_DEFAULT_MSG_ID           = 0x003F,
    SMMC_TAG_SHORT_MESSAGE               = 0x0040,
    SMMC_TAG_COMMAND_STATUS              = 0x0041,

    // [0x0050 ~ 0x00FF] for dsmp
    DSMP_TAG_INFO_CODE                   = 0x0050,
    DSMP_TAG_INFO_VALUE                  = 0x0051,
    DSMP_TAG_SEND_ADDR_DEVICE_TYPE       = 0x0052,
    DSMP_TAG_DEST_ADDR_DEVICE_TYPE       = 0x0053,
    DSMP_TAG_SEND_ADDR_DEVICE_ID         = 0x0054,
    DSMP_TAG_DEST_ADDR_DEVICE_ID         = 0x0055,
    DSMP_TAG_FEEUSER_ID_USER_ID_TYPE     = 0x0056,
    DSMP_TAG_DESTUSER_ID_USER_ID_TYPE    = 0x0057,
    DSMP_TAG_FEEUSER_ID_MSISDN           = 0x0058,
    DSMP_TAG_DESTUSER_ID_MSISDN          = 0x0059,
    DSMP_TAG_FEEUSER_ID_PSEUDO_CODE      = 0x005A,
    DSMP_TAG_DESTUSER_ID_PSEUDO_CODE     = 0x005B,
    DSMP_TAG_SERVICE_ID_TYPE             = 0x005C,
    DSMP_TAG_COMMON_SPID                 = 0x005D,
    DSMP_TAG_SMS_CDR_SPID                = 0x005E,
    DSMP_TAG_MMS_CDR_SPID                = 0x005F,
    DSMP_TAG_KJAVA_CDR_SPID              = 0x0060,
    DSMP_TAG_WAP_CDR_SPID                = 0x0061,
    DSMP_TAG_COMMON_SP_SERVICE_ID        = 0x0062,
    DSMP_TAG_SMS_CDR_SP_SERVICE_ID       = 0x0063,
    DSMP_TAG_MMS_CDR_SP_SERVICE_ID       = 0x0064,
    DSMP_TAG_KJAVA_CDR_SP_SERVICE_ID     = 0x0065,
    DSMP_TAG_WAP_CDR_SP_SERVICE_ID       = 0x0066,
    DSMP_TAG_ACCESS_NO                   = 0x0067,
    DSMP_TAG_FEATURE_STR                 = 0x0068,
    DSMP_TAG_REC_TYPE                    = 0x0069,
    DSMP_TAG_SMS_SEQ                     = 0x006A,
    DSMP_TAG_COMMON_USER_TYPE_INT        = 0x006B,
    DSMP_TAG_SMS_CDR_USER_TYPE_INT       = 0x006C,
    DSMP_TAG_MMS_CDR_USER_TYPE_INT       = 0x006D,
    DSMP_TAG_KJAVA_CDR_USER_TYPE_INT     = 0x006E,
    DSMP_TAG_MAIL_CDR_USER_TYPE_STR      = 0x006F,
    DSMP_TAG_WAP_CDR_USER_TYPE_STR       = 0x0070,
    DSMP_TAG_CHARGE_DN                   = 0x0071,
    DSMP_TAG_THIRD_DN                    = 0x0072,
    DSMP_TAG_CHARGE_TYPE                 = 0x0073,
    DSMP_TAG_SMS_CDR_INFO_FEE            = 0x0074,
    DSMP_TAG_WAP_CDR_INFO_FEE            = 0x0075,
    DSMP_TAG_SMS_MONTH_FEE               = 0x0076,
    DSMP_TAG_WAP_MONTH_FEE               = 0x0077,
    DSMP_TAG_SEND_STAT                   = 0x0078,
    DSMP_TAG_PRIORITY                    = 0x0079,
    DSMP_TAG_MSG_LEN                     = 0x007A,
    DSMP_TAG_CHARGE_PROV                 = 0x007B,
    DSMP_TAG_SMS_CDR_ISMG_ID             = 0x007C,
    DSMP_TAG_MAIL_CDR_ISMG_ID            = 0x007D,
    DSMP_TAG_FORWD_ISMG_ID               = 0x007E,
    DSMP_TAG_SMSC_ID                     = 0x007F,
    DSMP_TAG_APPLY_TIME                  = 0x0080,
    DSMP_TAG_FINISH_TIME                 = 0x0081,
    DSMP_TAG_COMMON_MSG_ID               = 0x0082,
    DSMP_TAG_KJAVA_CDR_MSG_ID            = 0x0083,
    DSMP_TAG_MAIL_CDR_MSG_ID             = 0x0084,
    DSMP_TAG_MMS_CDR_CHG_MSISDN          = 0x0085,
    DSMP_TAG_KJAVA_CDR_CHG_MSISDN        = 0x0086,
    DSMP_TAG_MAIL_CDR_CHG_MSISDN         = 0x0087,
    DSMP_TAG_ALIAS                       = 0x0088,
    DSMP_TAG_BOX_SIZE                    = 0x0089,
    DSMP_TAG_VISIT_TYPE                  = 0x008A,
    DSMP_TAG_ACTION_TYPE                 = 0x008B,
    DSMP_TAG_MAIL_DEVICE_CODE            = 0x008C,
    DSMP_TAG_UMS_DEVICE_CODE             = 0x008D,
    DSMP_TAG_MMS_CDR_SERVICE_ID          = 0x008E,
    DSMP_TAG_MAIL_CDR_SERVICE_ID         = 0x008F,
    DSMP_TAG_KJAVA_CDR_WAP_GWID          = 0x0090,
    DSMP_TAG_MAIL_CDR_WAP_GWID           = 0x0091,
    DSMP_TAG_ACCESS_IP                   = 0x0092,
    DSMP_TAG_KJAVA_CDR_ACCESS_PROV       = 0x0093,
    DSMP_TAG_MAIL_CDR_ACCESS_PROV        = 0x0094,
    DSMP_TAG_KJAVA_CDR_START_TIME        = 0x0095,
    DSMP_TAG_WAP_CDR_START_TIME          = 0x0096,
    DSMP_TAG_MAIL_CDR_START_TIME         = 0x0097,
    DSMP_TAG_KJAVA_CDR_END_TIME          = 0x0098,
    DSMP_TAG_MAIL_CDR_END_TIME           = 0x0099,
    DSMP_TAG_KJAVA_CDR_TIME_LENGTH       = 0x009A,
    DSMP_TAG_MAIL_CDRTIME_LENGTH         = 0x009B,
    DSMP_TAG_KJAVA_CDR_SIZE              = 0x009C,
    DSMP_TAG_MAIL_CDR_SIZE               = 0x009D,
    DSMP_TAG_KJAVA_CDR_CHG_TYPE          = 0x009E,
    DSMP_TAG_MAIL_CDR_CHG_TYPE           = 0x009F,
    DSMP_TAG_MMS_CDR_COST                = 0x00A0,
    DSMP_TAG_KJAVA_CDR_COST              = 0x00A1,
    DSMP_TAG_MAIL_CDR_COST               = 0x00A2,
    DSMP_TAG_KJAVA_CDR_DICOUNT           = 0x00A3,
    DSMP_TAG_MAIL_CDR_DICOUNT            = 0x00A4,
    DSMP_TAG_CALLER_ID                   = 0x00A5,
    DSMP_TAG_CALLEE_ID                   = 0x00A6,
    DSMP_TAG_UMSCALL_TYPE                = 0x00A7,
    DSMP_TAG_MAIL_CDR_BEARER_TYPE_INT    = 0x00A8,
    DSMP_TAG_MMS_CDR_BEARER_TYPE_STR     = 0x00A9,
    DSMP_TAG_KJAVA_CDR_BEARER_TYPE_STR   = 0x00AA,
    DSMP_TAG_WAP_CDR_BEARER_TYPE_STR     = 0x00AB,
    DSMP_TAG_KJAVA_CDR_STATUS_CODE       = 0x00AC,
    DSMP_TAG_MAIL_CDR_STATUS_CODE        = 0x00AD,
    DSMP_TAG_VALUE_TYPE                  = 0x00AE,
    DSMP_TAG_KJAVA_CDR_VALUED_PERIOD     = 0x00AF,
    DSMP_TAG_MAIL_CDR_VALUED_PERIOD      = 0x00B0,
    DSMP_TAG_SEQUENCE                    = 0x00B1,
    DSMP_TAG_MMS_CDR_TYPE_INT            = 0x00B2,
    DSMP_TAG_WAP_CDR_TYPE_STR            = 0x00B3,
    DSMP_TAG_WAP_GATEWAY_ID              = 0x00B4,
    DSMP_TAG_SP_GATEWAY_ID               = 0x00B5,
    DSMP_TAG_SERVICE_GRADE_ID            = 0x00B6,
    DSMP_TAG_DISCOUNT                    = 0x00B7,
    DSMP_TAG_SERVICE_ATTR                = 0x00B8,
    DSMP_TAG_STOP_TIME                   = 0x00B9,
    DSMP_TAG_CONTENT_LENGTH              = 0x00BA,
    DSMP_TAG_REGION_CODE                 = 0x00BB,
    DSMP_TAG_ACCESS_REGION               = 0x00BC,
    DSMP_TAG_USER_CHARGE_TYPE            = 0x00BD,
    DSMP_TAG_MMS_SPECIFIC_MESSAGE_ID     = 0x00BE,
    DSMP_TAG_IMSI                        = 0x00BF,
    DSMP_TAG_SOURCE_ADDRESS              = 0x00C0,
    DSMP_TAG_RECEIVE_ADDRESS             = 0x00C1,
    DSMP_TAG_TRANS_MSISDN                = 0x00C2,
    DSMP_TAG_INFO_TYPE                   = 0x00C3,
    DSMP_TAG_APP_TYPE                    = 0x00C4,
    DSMP_TAG_FOWD_COPY_TYPE              = 0x00C5,
    DSMP_TAG_BILLING_TYPE                = 0x00C6,
    DSMP_TAG_MM_SIZE                     = 0x00C7,
    DSMP_TAG_STORE_PERIOD                = 0x00C8,
    DSMP_TAG_IP_ADDRESS                  = 0x00C9,
    DSMP_TAG_MM_STATUS_CODE              = 0x00CA,
    DSMP_TAG_SOURCE_MMSC_ID              = 0x00CB,
    DSMP_TAG_RECEIVE_MMSC_ID             = 0x00CC,
    DSMP_TAG_USER_SOURCE_ID              = 0x00CD,
    DSMP_TAG_REVEICE_TIME                = 0x00CE,
    DSMP_TAG_SEND_TIME                   = 0x00CF,
    DSMP_TAG_FIRST_SEND_TIME             = 0x00D0,
    DSMP_TAG_MM_COUTENT_TYPE             = 0x00D1,
    DSMP_TAG_MM_TYPE                     = 0x00D2,
    DSMP_TAG_MESSAGE_PRIORITY            = 0x00D3,
    DSMP_TAG_REPORT_CLAIM                = 0x00D4,
    DSMP_TAG_ADDRESS_HIDE                = 0x00D5,
    DSMP_TAG_SECURITY_LEVEL              = 0x00D6,
    DSMP_TAG_CONTENT_ADAP                = 0x00D7,
    DSMP_TAG_SEQUENCE_ID                 = 0x00D8,
    DSMP_TAG_SOURCE_TYPE                 = 0x00D9,
    DSMP_TAG_DEVICE_CODE                 = 0x00DA,
    DSMP_TAG_SERVICE_RANGE               = 0x00DB,
    DSMP_TAG_MSG_PRI                     = 0x00DC,
    DSMP_TAG_TRANSACTION_ID              = 0x00DD,
    DSMP_TAG_VERSION                     = 0x00DE,
    DSMP_TAG_MSG_TYPE                    = 0x00DF,
    DSMP_TAG_HRET                        = 0x00E0,
    DSMP_TAG_PASSWORD                    = 0x00E1,
    DSMP_TAG_IPADDR                      = 0x00E2,
    DSMP_TAG_LINK_ID                     = 0x00E3,
    DSMP_TAG_SERVICE_TYPE                = 0x00E4,
    DSMP_TAG_FEE_TYPE                    = 0x00E5,
    DSMP_TAG_FEE_CODE                    = 0x00E6,
    DSMP_TAG_FEE_MSISDN                  = 0x00E7,
    DSMP_TAG_DEST_MSISDN                 = 0x00E8,
    DSMP_TAG_FEE_PSEUDO_CODE             = 0x00E9,
    DSMP_TAG_DEST_PSEUDO_CODE            = 0x00EA,
    DSMP_TAG_SEND_SP_USERID_TYPE         = 0x00EB,
    DSMP_TAG_OPER_TYPE                   = 0x00EC,
    DSMP_TAG_CONNECT_DEVICE_ID           = 0x00ED,
    DSMP_TAG_ORIGINAL_MSG_ID             = 0x00EE,
    DSMP_TAG_RESULT                      = 0x00EF,
    DSMP_TAG_PLATFORM_TYPE               = 0x00F0,
    DSMP_TAG_MONEY                       = 0x00F1,
    DSMP_TAG_FEEUSER_TYPE                = 0x00F2,
    DSMP_TAG_DESTUSER_TYPE               = 0x00F3,
    DSMP_TAG_STATUS                      = 0x00F4,
    DSMP_TAG_ACTION_ID                   = 0x00F5,
    DSMP_TAG_ACTION_REASON_ID            = 0x00F6,
    DSMP_TAG_ACCESS_MODE                 = 0x00F7,
    DSMP_TAG_MSGFMT                      = 0x00F8,

    // [0x0100 ~ 0x010F] route server (scp)
    ROUTE_TAG_SCP_RES_NUM   = 0x0100,
    ROUTE_TAG_SCP_ID        = 0x0101,
    ROUTE_TAG_SCP_IP        = 0x0102,
    ROUTE_TAG_SCP_PORT      = 0x0103,
    ROUTE_TAG_SCP_ACCOUNT   = 0x0104,
    ROUTE_TAG_SCP_PASSWORD  = 0x0105,
    ROUTE_TAG_SCP_CONNNUM   = 0x0106,
    ROUTE_TAG_SCP_MSISDN    = 0x0107,

    // [[0x0110 ~ 0x011F] sequence server
    SEQ_TAG_COUNT           = 0x0110,
    SEQ_TAG_TIME            = 0x0111,
    SEQ_TAG_START           = 0x0112,
    SEQ_TAG_END             = 0x0113,

    BENC_TAG_UNKNOWN = 0xFFFF
};


ANF_NAMESPACE_END

#endif // ANF_BENCODINGMESSAGE_H

